In [5]:
import polars as pl
import os

In [16]:
ruta_data = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/Ruta a la electrificación de la Movilidad/Datos/2015_01.parquet"
)

In [26]:
ruta_data["CATEGORÍA_VEHÍCULO_ELÉCTRICO"].unique()

shape: (5,)
Series: 'CATEGORÍA_VEHÍCULO_ELÉCTRICO' [str]
[
	null
	"HEV"
	"PHEV"
	"BEV"
	"REEV"
]

In [28]:
personas = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Personas_municipios_2022-01-01_2022-01-06_v2.parquet"
)
overnight = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Pernoctaciones_municipios_2022-01-01_2022-01-06_v2.parquet"
)
trips = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Viajes_municipios_2022-01-01_2022-01-06_v2.parquet"
)

In [24]:
personas.head()

shape: (5, 6)
┌────────────┬─────────────────────┬──────┬────────┬─────────────────┬─────────┐
│ date       ┆ overnight_stay_area ┆ age  ┆ gender ┆ number_of_trips ┆ people  │
│ ---        ┆ ---                 ┆ ---  ┆ ---    ┆ ---             ┆ ---     │
│ str        ┆ str                 ┆ str  ┆ str    ┆ str             ┆ f64     │
╞════════════╪═════════════════════╪══════╪════════╪═════════════════╪═════════╡
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 0               ┆ 244.54  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 1               ┆ 34.94   │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2               ┆ 64.971  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2+              ┆ 89.423  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ female ┆ 0               ┆ 164.802 │
└────────────┴─────────────────────┴──────┴────────┴─────────────────┴─────────┘

In [29]:
overnight.head()

shape: (5, 4)
┌────────────┬────────────────┬─────────────────────┬──────────┐
│ date       ┆ residence_area ┆ overnight_stay_area ┆ people   │
│ ---        ┆ ---            ┆ ---                 ┆ ---      │
│ str        ┆ str            ┆ str                 ┆ f64      │
╞════════════╪════════════════╪═════════════════════╪══════════╡
│ 2022-01-01 ┆ 01001          ┆ 01001               ┆ 2447.613 │
│ 2022-01-01 ┆ 01001          ┆ 01017_AM            ┆ 9.0      │
│ 2022-01-01 ┆ 01001          ┆ 01047_AM            ┆ 2.514    │
│ 2022-01-01 ┆ 01001          ┆ 01051               ┆ 5.78     │
│ 2022-01-01 ┆ 01001          ┆ 01059               ┆ 181.97   │
└────────────┴────────────────┴─────────────────────┴──────────┘

In [30]:
trips.head()

shape: (5, 8)
┌────────────┬──────┬───────────┬──────────────┬─────────────┬─────────────┬─────────┬─────────────┐
│ date       ┆ hour ┆ id_origin ┆ id_destinati ┆ activity_or ┆ activity_de ┆ n_trips ┆ trips_total │
│ ---        ┆ ---  ┆ ---       ┆ on           ┆ igin        ┆ stination   ┆ ---     ┆ _length_km  │
│ str        ┆ i64  ┆ str       ┆ ---          ┆ ---         ┆ ---         ┆ f64     ┆ ---         │
│            ┆      ┆           ┆ str          ┆ str         ┆ str         ┆         ┆ f64         │
╞════════════╪══════╪═══════════╪══════════════╪═════════════╪═════════════╪═════════╪═════════════╡
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ home        ┆ other_frequ ┆ 2.605   ┆ 9.457       │
│            ┆      ┆           ┆              ┆             ┆ ent         ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_frequ ┆ home        ┆ 12.146  ┆ 65.663      │
│            ┆      ┆           ┆              ┆ ent         ┆             ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_frequ ┆ other_frequ ┆ 5.398   ┆ 32.272      │
│            ┆      ┆           ┆              ┆ ent         ┆ ent         ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_non_f ┆ home        ┆ 2.212   ┆ 5.645       │
│            ┆      ┆           ┆              ┆ requent     ┆             ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ work_or_stu ┆ home        ┆ 1.041   ┆ 4.629       │
│            ┆      ┆           ┆              ┆ dy          ┆             ┆         ┆             │
└────────────┴──────┴───────────┴──────────────┴─────────────┴─────────────┴─────────┴─────────────┘